### ISSUE TITLE
Create and populate marketing team in mozilla github org

### ISSUE THREAD

**Issue by jgmize** [mozilla/marketing#7]
- [X] create teams from button on https://github.com/orgs/mozilla/teams
- [ ] add [members](https://github.com/orgs/mozilla/teams/marketing/members)

**Comment by jgmize** [comment]
@kaykas I've invited you to become a member of the mozilla github organization and to the marketing team. Once you've accepted the invitation I will promote you to team maintainer so that you can add other members directly if you wish, and more importantly, you can delegate that responsibility to any other github account in the organization. I'll edit this comment later to add some links for additional context (and will check the box below along the way). In the meantime, I'll iterate through the internal phonebook and invite people myself.

- [ ] add links

**Comment by floatingatoll** [comment]
When adding members who aren't already in the Mozilla organization, please triple-check their GitHub username and copy-paste it rather than typing it into the "invite new member" form. I've witnessed people get their own GitHub username wrong in such a way that we would have invited a complete stranger into a private credentials repository had we not asked them to click https://github.com/theusernametheygaveus and confirm it was them, so it's critical to be absolutely certain that you're adding the right name.
